version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  app:
    container_name: app
    build:
      context: ./app
    depends_on:
      - db
    ports:
     - '8080:8080'
    links:
      - db
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGPASSWORD=example
      - PGDATABASE=postgres
      - PGPORT=5432
      - PORT=8080
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db:
    driver: local